### PR TITLE
[WIP] New feature `download` that automatically downloads the SDK

### PR DESCRIPTION
**Pull request by AlexApps99**
Everything is working (on Linux at least), this just needs testing on different platforms, and feature approval.

I may replace the `reqwest` dependency if it is too large, `curl` seems like a good alternative.

To use it just enable the feature `download`, and everything *should* work.

### CODE REVIEW

**Comment by AlexApps99** [comment]
Hey @ldesgoui, do you have any feedback on this? I have tested this on Linux and it works, if you could confirm it works on macOS and Windows that would be awesome :)

The test repository I used is [here](https://github.com/AlexApps99/discord-rust-test).

Note: The failing check seems to be a problem with the CI service.

**Comment by ldesgoui** [comment]
Hello,

First of all, thanks for the PR

As I mentioned to you in Discord, I believe it is good practice to have as little side effects as possible in Cargo build scripts, and so for various reasons.
Here are more issues I have with implementing this type of feature:
- I don't feel comfortable giving a direct path to developers, Discord ToS require to be read and approved
- The script comes down to downloading a file, unzipping it, and renaming a few things, I believe this fits nicely in documentation and build errors. If the current instructions are not good enough, we can make them better
- The SDK is updated in different intervals, how would someone opt into an update? (As far as I'm aware, there's no direct way to force a build script to run) Why should someone have to opt out? (Changes may cause builds to fail, making them have to revert to downlading a specific version and using the `link` feature) 

I'm happy to discuss and open to be convinced otherwise

I hope you understand my positions

Bests

**Comment by AlexApps99** [comment]
To respond to the points you've made:
- I agree that users should be exposed to the Discord ToS, that is something I may add to this PR, perhaps using the metadata table of `Cargo.toml` so the user has to include `agree_discord_tos = true` before it will build.
- While the process of setting up this is relatively simple, in some cases it is much more difficult to do it by hand (CI, for example). This is why I have made it a feature that users opt-in to, in the case that they need it to be done automatically.
- As for upgrading, although there's no way to rebuild a dependency, I could add an environment variable to force-rebuild the binding (and run the buildscript), and for downgrading it's quite unlikely to be needed as the Game SDK is guaranteed to be backwards-compatible and they do not offer downloads for older versions.

As for why I think that this feature is reasonable, most binding crates link to the system version of a library, and expose a feature to build from source directly.

Ultimately, the decision is yours though, if this doesn't fit for this then that's ok.

Thanks for the awesome library :)

**Comment by ldesgoui** [comment]
I think I'm willing to settle with a middle ground, I plan on updating the script to handle everything off the zipped SDK, all that would be needed from the user would be to download and point an environment variable to the path. That should help a lot with emboarding and CI.

I'm not sure I'll be using your code yet but I'd like to thank you nonetheless for your contribution.

**Comment by ldesgoui** [comment]
Hello @AlexApps99, apologies for forgetting to get back to this, I've tried my hand at making a solution that would please me, unfortunately I could not, the gist being handling a zip would end up making assumptions about the user's directory structure and create a directory at an arbitrary place, which I'm not comfortable with.
I will look into making the documentation better in order to ease the barrier of entry.
Apologies for the broken promise.
Bests

**Pull request closed without merging**
